theme: jekyll-theme-hacker
title: Notes, stories about a desperate developer
baseurl: "/"

plugins:
  - jekyll-optional-front-matter

lsi: false
safe: true
source: https://brucegithub.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
