theme: jekyll-theme-minimal
title: Notes, stories about a desperate developer

permalink:           pretty

paginate:         5
paginate_path:    '/blog/page:num'

source: https://brucegithub.github.io

